kind: Cluster
apiVersion: kind.x-k8s.io/v1alpha4
name: argocd
networking:
  apiServerAddress: "127.0.0.1"
  apiServerPort: 6443
nodes:
- role: control-plane
  # extraPortMappings:
  #   - containerPort: 443
  #     hostPort: 8443
  #     listenAddress: "127.0.0.1"
  #     protocol: TCP