applications:
- name: prometheus
  project: default
  namespace: default
  sources:
  - chart: kube-prometheus-stack
    repoURL: https://prometheus-community.github.io/helm-charts
    targetRevision: 70.3.0

